Repository fresh2you/fresh-api, pull requests merged in 2024-09, with the labels that each got.

#7 회원가입 기능 추가
  build.gradle
  src/main/java/com/zb/fresh_api/FreshApiApplication.java
  src/main/java/com/zb/fresh_api/api/common/exception/ErrorCode.java
  src/main/java/com/zb/fresh_api/api/config/SecurityConfig.java
  src/main/java/com/zb/fresh_api/api/controller/MemberController.java
  src/main/java/com/zb/fresh_api/api/dto/SignUpRequest.java
  src/main/java/com/zb/fresh_api/api/service/MemberService.java
  src/main/java/com/zb/fresh_api/api/validation/annotation/PasswordMatch.java
  src/main/java/com/zb/fresh_api/api/validation/validator/PasswordMatchValidator.java
  src/main/java/com/zb/fresh_api/domain/repository/MemberRepository.java
Labels: feat

#17 FEAT : 휴대폰 인증 기능 추가
  build.gradle
  src/main/java/com/zb/fresh_api/api/config/RedisConfig.java
  src/main/java/com/zb/fresh_api/api/controller/SmsController.java
  src/main/java/com/zb/fresh_api/api/service/SmsService.java
  src/main/java/com/zb/fresh_api/api/utils/RedisUtil.java
  src/main/java/com/zb/fresh_api/api/utils/SmsUtil.java
  src/main/java/com/zb/fresh_api/common/exception/ResponseCode.java
Labels: feat

#18 FEAT : 회원가입 API 공통화, 이메일 유효성 검증 위치 변경, 테스트 코드 변경, 회원가입 API 주석 작성 등
  src/main/java/com/zb/fresh_api/api/controller/MemberController.java
  src/main/java/com/zb/fresh_api/api/dto/SignUpRequest.java
  src/main/java/com/zb/fresh_api/api/service/MemberService.java
  src/test/java/com/zb/fresh_api/api/controller/MemberControllerTest.java
  src/test/java/com/zb/fresh_api/api/service/MemberServiceTest.java
Labels: fix, docs, refactor, test

#21 FEAT, REFACTOR, FIX : 휴대전화 인증 기능 변경, 제약 사항 수정
  src/main/java/com/zb/fresh_api/api/service/SmsService.java
  src/main/java/com/zb/fresh_api/api/utils/RedisUtil.java
  src/main/java/com/zb/fresh_api/api/utils/SmsUtil.java
  src/main/java/com/zb/fresh_api/common/constants/SmsConstants.java
  src/main/java/com/zb/fresh_api/common/exception/ResponseCode.java
Labels: fix, feat, refactor

#25 FEAT : 이메일 인증 기능 추가
  build.gradle
  src/main/java/com/zb/fresh_api/api/controller/Auth/EmailAuthController.java
  src/main/java/com/zb/fresh_api/api/controller/Auth/SmsAuthController.java
  src/main/java/com/zb/fresh_api/api/enums/VerificationType.java
  src/main/java/com/zb/fresh_api/api/service/EmailService.java
  src/main/java/com/zb/fresh_api/api/service/SmsService.java
  src/main/java/com/zb/fresh_api/api/utils/EmailUtil.java
  src/main/java/com/zb/fresh_api/api/utils/RedisUtil.java
  src/main/java/com/zb/fresh_api/api/utils/SmsUtil.java
  src/main/java/com/zb/fresh_api/api/utils/VerificationCodeUtil.java
  src/main/java/com/zb/fresh_api/common/constants/EmailConstants.java
  src/main/java/com/zb/fresh_api/common/constants/RedisConstants.java
  src/main/java/com/zb/fresh_api/common/constants/SmsConstants.java
  src/main/java/com/zb/fresh_api/common/exception/ResponseCode.java
  src/test/java/com/zb/fresh_api/api/controller/Auth/EmailAuthControllerTest.java
  src/test/java/com/zb/fresh_api/api/service/EmailServiceTest.java
Labels: feat, chore

#28 FEAT : 소셜 로그인 및 프로필 변경 기능 개발
  build.gradle
  src/main/java/com/zb/fresh_api/api/client/KakaoApiClient.java
  src/main/java/com/zb/fresh_api/api/client/KakaoAuthClient.java
  src/main/java/com/zb/fresh_api/api/config/FeignClientConfig.java
  src/main/java/com/zb/fresh_api/api/config/SecurityConfig.java
  src/main/java/com/zb/fresh_api/api/controller/MemberController.java
  src/main/java/com/zb/fresh_api/api/dto/LoginMember.java
  src/main/java/com/zb/fresh_api/api/dto/request/LoginRequest.java
  src/main/java/com/zb/fresh_api/api/dto/request/OauthLoginRequest.java
  src/main/java/com/zb/fresh_api/api/dto/request/UpdateProfileRequest.java
  src/main/java/com/zb/fresh_api/api/dto/response/LoginResponse.java
  src/main/java/com/zb/fresh_api/api/dto/response/OauthLoginMember.java
  src/main/java/com/zb/fresh_api/api/dto/response/OauthLoginResponse.java
  src/main/java/com/zb/fresh_api/api/factory/OauthProviderFactory.java
  src/main/java/com/zb/fresh_api/api/provider/TokenProvider.java
  src/main/java/com/zb/fresh_api/api/provider/oauth/KakaoProvider.java
  src/main/java/com/zb/fresh_api/api/provider/oauth/OauthProvider.java
  src/main/java/com/zb/fresh_api/api/resolver/AuthorizedMemberResolver.java
  src/main/java/com/zb/fresh_api/api/service/MemberService.java
  src/main/java/com/zb/fresh_api/api/utils/SmsUtil.java
  src/main/java/com/zb/fresh_api/common/constants/SecurityConstants.java
  src/main/java/com/zb/fresh_api/domain/dto/member/KakaoAccount.java
  src/main/java/com/zb/fresh_api/domain/dto/member/KakaoUser.java
  src/main/java/com/zb/fresh_api/domain/dto/member/OauthUser.java
  src/main/java/com/zb/fresh_api/domain/dto/token/KakaoToken.java
  src/main/java/com/zb/fresh_api/domain/dto/token/OauthToken.java
  src/main/java/com/zb/fresh_api/domain/dto/token/Token.java
  src/main/java/com/zb/fresh_api/domain/entity/member/Member.java
  src/main/java/com/zb/fresh_api/domain/repository/writer/MemberWriter.java
  src/main/resources/application.yml
  src/test/java/com/zb/fresh_api/api/service/MemberServiceTest.java
  src/test/java/com/zb/fresh_api/common/base/ServiceTest.java
Labels: feat, refactor, test

#31 FEAT : 회원가입 시 포인트 기능 추가
  src/main/java/com/zb/fresh_api/api/controller/TermsController.java
  src/main/java/com/zb/fresh_api/api/service/MemberService.java
  src/main/java/com/zb/fresh_api/api/utils/SmsUtil.java
  src/main/java/com/zb/fresh_api/domain/entity/member/Member.java
  src/main/java/com/zb/fresh_api/domain/entity/point/Point.java
  src/main/java/com/zb/fresh_api/domain/entity/point/PointHistory.java
  src/main/java/com/zb/fresh_api/domain/enums/point/PointStatus.java
  src/main/java/com/zb/fresh_api/domain/enums/point/PointTransactionType.java
  src/main/java/com/zb/fresh_api/domain/repository/jpa/PointHistoryRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/jpa/PointJpaRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/query/PointHistoryQueryRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/query/PointQueryRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/writer/PointHistoryWriter.java
  src/main/java/com/zb/fresh_api/domain/repository/writer/PointWriter.java
  src/test/java/com/zb/fresh_api/api/controller/Auth/EmailAuthControllerTest.java
  src/test/java/com/zb/fresh_api/api/controller/MemberControllerTest.java
  src/test/java/com/zb/fresh_api/api/controller/TermsControllerTest.java
  src/test/java/com/zb/fresh_api/api/service/MemberServiceTest.java
Labels: feat

#33 FEAT : 상품 관련 API 추가
  src/main/java/com/zb/fresh_api/api/controller/Auth/SmsAuthController.java
  src/main/java/com/zb/fresh_api/api/controller/CategoryController.java
  src/main/java/com/zb/fresh_api/api/controller/ProductController.java
  src/main/java/com/zb/fresh_api/api/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/zb/fresh_api/api/dto/request/AddProductRequest.java
  src/main/java/com/zb/fresh_api/api/dto/request/DeleteProductRequest.java
  src/main/java/com/zb/fresh_api/api/dto/request/GetProductDetailRequest.java
  src/main/java/com/zb/fresh_api/api/dto/request/UpdateProductRequest.java
  src/main/java/com/zb/fresh_api/api/dto/response/AddProductResponse.java
  src/main/java/com/zb/fresh_api/api/dto/response/CategoryDto.java
  src/main/java/com/zb/fresh_api/api/dto/response/DeleteProductResponse.java
  src/main/java/com/zb/fresh_api/api/dto/response/GetAllCategoryResponse.java
  src/main/java/com/zb/fresh_api/api/dto/response/GetProductDetailResponse.java
  src/main/java/com/zb/fresh_api/api/dto/response/SubCategoryDto.java
  src/main/java/com/zb/fresh_api/api/dto/response/UpdateProductResponse.java
  src/main/java/com/zb/fresh_api/api/service/CategoryService.java
  src/main/java/com/zb/fresh_api/api/service/ProductService.java
  src/main/java/com/zb/fresh_api/api/service/SmsService.java
  src/main/java/com/zb/fresh_api/common/exception/ResponseCode.java
  src/main/java/com/zb/fresh_api/domain/entity/category/Category.java
  src/main/java/com/zb/fresh_api/domain/entity/member/Member.java
  src/main/java/com/zb/fresh_api/domain/entity/product/Product.java
  src/main/java/com/zb/fresh_api/domain/entity/product/ProductSnapshot.java
  src/main/java/com/zb/fresh_api/domain/repository/jpa/CategoryJpaRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/jpa/ProductJpaRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/jpa/ProductSnapshotJpaRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/query/CategoryQueryRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/query/MemberQueryRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/query/ProductQueryRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/reader/CategoryReader.java
  src/main/java/com/zb/fresh_api/domain/repository/reader/MemberReader.java
  src/main/java/com/zb/fresh_api/domain/repository/reader/ProductReader.java
  src/main/java/com/zb/fresh_api/domain/repository/writer/ProductSnapshotWriter.java
  src/main/java/com/zb/fresh_api/domain/repository/writer/ProductWriter.java
  src/test/java/com/zb/fresh_api/api/service/CategoryServiceTest.java
  src/test/java/com/zb/fresh_api/api/service/ProductServiceTest.java
Labels: feat, test

#46 REFACTOR : 주문 내역 테이블 리팩토링
  src/main/java/com/zb/fresh_api/domain/entity/member/Customer.java
  src/main/java/com/zb/fresh_api/domain/entity/order/ProductOrder.java
Labels: refactor

#62 FIX : 상품 수정, 상품 등록 API 사진 url 업로드 로직 수정 [#59]
  src/main/java/com/zb/fresh_api/api/service/ProductService.java
Labels: fix

#64 FEAT : 추천 서비스 개발
  src/main/java/com/zb/fresh_api/api/controller/RecommendController.java
  src/main/java/com/zb/fresh_api/api/dto/request/LoadProductRecommendListRequest.java
  src/main/java/com/zb/fresh_api/api/dto/response/LoadProductRecommendListResponse.java
  src/main/java/com/zb/fresh_api/api/service/RecommendService.java
  src/main/java/com/zb/fresh_api/common/constants/SecurityConstants.java
  src/main/java/com/zb/fresh_api/domain/dto/recommend/CategoryProductOrder.java
  src/main/java/com/zb/fresh_api/domain/dto/recommend/RecommendProductSummary.java
  src/main/java/com/zb/fresh_api/domain/dto/recommend/SellerProductOrder.java
  src/main/java/com/zb/fresh_api/domain/entity/address/DeliveryAddress.java
  src/main/java/com/zb/fresh_api/domain/entity/product/Product.java
  src/main/java/com/zb/fresh_api/domain/repository/query/OrderQueryRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/query/ProductQueryRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/reader/OrderReader.java
  src/main/java/com/zb/fresh_api/domain/repository/reader/ProductReader.java
  src/test/java/com/zb/fresh_api/api/service/RecommendServiceTest.java
Labels: feat

#56 Feat/#26 채팅 차단기능
  src/main/java/com/zb/fresh_api/api/config/ChattingConfig.java
  src/main/java/com/zb/fresh_api/api/controller/ChatBlockController.java
  src/main/java/com/zb/fresh_api/api/controller/ChatController.java
  src/main/java/com/zb/fresh_api/api/service/ChatBlockService.java
  src/main/java/com/zb/fresh_api/api/service/ChatMessageService.java
  src/main/java/com/zb/fresh_api/api/service/ChatRoomService.java
  src/main/java/com/zb/fresh_api/common/exception/ResponseCode.java
  src/main/java/com/zb/fresh_api/domain/dto/chat/ChatMessageDto.java
  src/main/java/com/zb/fresh_api/domain/entity/chat/ChatBlock.java
  src/main/java/com/zb/fresh_api/domain/repository/jpa/ChatBlockRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/reader/ChatRoomMemberReader.java
  src/test/java/com/zb/fresh_api/api/controller/ChatControllerTest.java
  src/test/java/com/zb/fresh_api/api/service/ChatRoomServiceTest.java
  src/test/java/com/zb/fresh_api/api/websocket/WebSocketConfigTest.java
Labels: feat

#72 Feat/#26 Chatblock Entity 수정
  src/main/java/com/zb/fresh_api/domain/entity/chat/ChatBlock.java
Labels: feat

#73 FEAT : 닉네임 및 회원 정보 응답 값 변경
  src/main/java/com/zb/fresh_api/api/service/MemberService.java
  src/main/java/com/zb/fresh_api/api/utils/RandomUtil.java
  src/main/java/com/zb/fresh_api/common/constants/AppConstants.java
  src/main/java/com/zb/fresh_api/common/exception/ResponseCode.java
  src/main/java/com/zb/fresh_api/domain/dto/member/LoginMember.java
  src/main/java/com/zb/fresh_api/domain/dto/member/MemberWithPoint.java
  src/main/java/com/zb/fresh_api/domain/dto/member/OauthLoginMember.java
  src/main/java/com/zb/fresh_api/domain/entity/member/Word.java
  src/main/java/com/zb/fresh_api/domain/enums/member/WordType.java
  src/main/java/com/zb/fresh_api/domain/repository/jpa/MemberJpaRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/jpa/WordJpaRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/query/MemberQueryRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/reader/MemberReader.java
  src/main/java/com/zb/fresh_api/domain/repository/reader/WordReader.java
  src/main/resources/sql/insert.sql
Labels: feat

#74 FIX : swagger url 수정
  src/main/java/com/zb/fresh_api/api/controller/ChatBlockController.java
  src/main/java/com/zb/fresh_api/api/controller/ChatController.java
Labels: fix

#78 FIX : 토큰 인증 시 Provider 분리
  src/main/java/com/zb/fresh_api/api/principal/CustomUserDetailsService.java
  src/main/java/com/zb/fresh_api/domain/repository/jpa/MemberJpaRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/reader/MemberReader.java
Labels: fix

#79 API-ISSUE : 배송지 목록 조회 API 휴대전화 포함
  src/main/java/com/zb/fresh_api/api/dto/response/AddressDto.java
Labels: api-issue

#80 FEAT : 회원 정보 조회 기능 추가
  src/main/java/com/zb/fresh_api/api/controller/MemberController.java
  src/main/java/com/zb/fresh_api/api/dto/response/LoadProfileResponse.java
  src/main/java/com/zb/fresh_api/api/service/MemberService.java
Labels: feat

#82 FEAT : 엘라스틱 캐시 도입 (파라미터 스토어 URL 입력)
  src/main/resources/application-dev.yml
Labels: feat

#84 FIX : 회원가입 Provider에따른 예외 처리 추가
  src/main/java/com/zb/fresh_api/api/controller/MemberController.java
  src/main/java/com/zb/fresh_api/api/dto/SignUpRequest.java
  src/main/java/com/zb/fresh_api/api/service/MemberService.java
  src/main/java/com/zb/fresh_api/common/constants/AppConstants.java
  src/main/java/com/zb/fresh_api/common/exception/ResponseCode.java
  src/main/java/com/zb/fresh_api/domain/entity/member/Member.java
  src/test/java/com/zb/fresh_api/api/controller/MemberControllerTest.java
  src/test/java/com/zb/fresh_api/api/service/MemberServiceTest.java
Labels: fix, feat
