Repository fresh2you/fresh-api, pull requests merged in 2024-10, with the labels that each got.

#87 FIX : 프로필 변경 API 스웨거에서 사진 등록 불가한 문제 수정
  src/main/java/com/zb/fresh_api/api/controller/MemberController.java
Labels: fix

#89 FEAT : 판매자 인증 문자 코드 전송 API 수정
  src/main/java/com/zb/fresh_api/api/controller/Auth/SmsAuthController.java
  src/main/java/com/zb/fresh_api/api/service/SmsService.java
  src/main/java/com/zb/fresh_api/common/exception/ResponseCode.java
Labels: feat

#91 refactor : 소셜 로그인 회원가입시 토큰 응답 [#90]
  src/main/java/com/zb/fresh_api/api/controller/MemberController.java
  src/main/java/com/zb/fresh_api/api/dto/response/SignupResponse.java
  src/main/java/com/zb/fresh_api/api/service/MemberService.java
Labels: refactor

#92 FEAT : 이력 기반 추천 상품 가져오는 API 상품 id값 추가
  src/main/java/com/zb/fresh_api/domain/dto/recommend/RecommendProductSummary.java
  src/main/java/com/zb/fresh_api/domain/repository/query/ProductQueryRepository.java
Labels: feat

#96 FEAT : 판매자 상품 목록 조회 API 추가
  src/main/java/com/zb/fresh_api/api/controller/ProductController.java
  src/main/java/com/zb/fresh_api/api/dto/request/GetSellerProducts.java
  src/main/java/com/zb/fresh_api/api/service/ProductService.java
  src/main/java/com/zb/fresh_api/common/exception/ResponseCode.java
  src/main/java/com/zb/fresh_api/domain/repository/query/ProductQueryRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/reader/ProductReader.java
Labels: feat

#101 FIX : 상품 조회시 삭제된 상품 조회안되도록 수정
  src/main/java/com/zb/fresh_api/domain/repository/query/ProductQueryRepository.java
Labels: fix

#102 fix : 상품 조회시 삭제된 상품 조회안되도록 수정 [#100]
  src/main/java/com/zb/fresh_api/domain/repository/query/ProductQueryRepository.java
Labels: fix

#104 FIX : 전체상품 조회 시 삭제된 데이터 조회 에러
  src/main/java/com/zb/fresh_api/domain/repository/query/ProductQueryRepository.java
Labels: fix

#109 FIX : 로그인에서 비밀번호 불일치 할 시 반환 코드 변경
  src/main/java/com/zb/fresh_api/api/service/MemberService.java
  src/main/java/com/zb/fresh_api/common/exception/ResponseCode.java
Labels: fix

#108 Fix : 탈퇴된 이메일 사용불가 문제
  src/main/java/com/zb/fresh_api/domain/repository/jpa/MemberJpaRepository.java
  src/main/java/com/zb/fresh_api/domain/repository/reader/MemberReader.java
Labels: fix
